#!/usr/bin/env python3
"""
Convert PNG images to LVGL 8.x TRUE_COLOR_ALPHA format C arrays.
Generates both .c and .h files for easy integration.

Usage:
    python3 png2icons.py <icons_dir> <output_c> <output_h>

Example:
    python3 png2icons.py assets/icons src/app/icons.c src/app/icons.h
"""

import sys
import os
from PIL import Image


def png_to_lvgl_rgba(img_path, symbol_name):
    """Convert PNG to LVGL TRUE_COLOR_ALPHA format data."""
    
    # Read the PNG and convert to RGBA
    img = Image.open(img_path)
    img = img.convert('RGBA')
    
    width, height = img.size
    pixels = list(img.getdata())
    
    # Generate pixel data
    # LVGL TRUE_COLOR_ALPHA stores each pixel as RGB565 (2 bytes) + Alpha (1 byte)
    # Total: 3 bytes per pixel
    byte_array = []
    
    for r, g, b, a in pixels:
        # Convert RGB888 to RGB565
        r5 = (r >> 3) & 0x1F
        g6 = (g >> 2) & 0x3F
        b5 = (b >> 3) & 0x1F
        rgb565 = (r5 << 11) | (g6 << 5) | b5
        
        # Store as little-endian RGB565 + alpha
        byte_array.append(rgb565 & 0xFF)        # Low byte of RGB565
        byte_array.append((rgb565 >> 8) & 0xFF) # High byte of RGB565
        byte_array.append(a)                     # Alpha
    
    return width, height, byte_array


def generate_icons(icons_dir, output_cpp, output_h):
    """Generate icons.cpp and icons.h from PNG files."""
    
    # Find all PNG files
    png_files = sorted([f for f in os.listdir(icons_dir) if f.endswith('.png')])
    
    if not png_files:
        print(f'Error: No PNG files found in {icons_dir}')
        sys.exit(1)
    
    print(f'Found {len(png_files)} PNG files:')
    for f in png_files:
        print(f'  - {f}')
    
    icons_data = []
    
    # Process each PNG
    for png_file in png_files:
        png_path = os.path.join(icons_dir, png_file)
        symbol_name = os.path.splitext(png_file)[0]  # e.g., "grid" from "grid.png"
        
        width, height, byte_array = png_to_lvgl_rgba(png_path, symbol_name)
        icons_data.append({
            'name': symbol_name,
            'width': width,
            'height': height,
            'data': byte_array,
            'map_name': f'{symbol_name}_map'
        })
        
        print(f'  ✓ Processed {png_file}: {width}x{height}, {len(byte_array)} bytes')
    
    # Generate .h file
    with open(output_h, 'w') as f:
        f.write('/*\n')
        f.write(' * Auto-generated icon definitions\n')
        f.write(' * Generated by tools/png2icons.py\n')
        f.write(' * DO NOT EDIT MANUALLY\n')
        f.write(' */\n\n')
        f.write('#ifndef ICONS_H\n')
        f.write('#define ICONS_H\n\n')
        f.write('#include <lvgl.h>\n\n')
        f.write('// Icon declarations\n')
        for icon in icons_data:
            f.write(f'extern const lv_img_dsc_t {icon["name"]};\n')
        f.write('\n#endif // ICONS_H\n')
    
    print(f'\n✓ Generated {output_h}')
    
    # Generate .c file
    with open(output_c, 'w') as f:
        f.write('#include <lvgl.h>\n\n')
        f.write('#ifndef LV_ATTRIBUTE_MEM_ALIGN\n')
        f.write('#define LV_ATTRIBUTE_MEM_ALIGN\n')
        f.write('#endif\n\n')
        f.write('#ifndef LV_ATTRIBUTE_IMG_\n')
        f.write('#define LV_ATTRIBUTE_IMG_\n')
        f.write('#endif\n\n')
        
        for icon in icons_data:
            # Write map data
            f.write(f'// {icon["width"]}x{icon["height"]} RGBA icon: {icon["name"]}\n')
            f.write(f'const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_IMG_ uint8_t {icon["map_name"]}[] = {{\n')
            
            # Write bytes in rows of 12 (4 pixels * 3 bytes each)
            data = icon['data']
            for i in range(0, len(data), 12):
                row = data[i:i+12]
                f.write('  ' + ', '.join(f'0x{b:02x}' for b in row))
                if i + 12 < len(data):
                    f.write(',')
                f.write('\n')
            
            f.write('};\n\n')
            
            # Write image descriptor (LVGL 8.x format, C-style initialization)
            f.write(f'const lv_img_dsc_t {icon["name"]} = {{\n')
            f.write('  {  // header\n')
            f.write('    LV_IMG_CF_TRUE_COLOR_ALPHA,  // cf\n')
            f.write('    0,  // always_zero\n')
            f.write('    0,  // reserved\n')
            f.write(f'    {icon["width"]},  // w\n')
            f.write(f'    {icon["height"]},  // h\n')
            f.write('  },\n')
            f.write(f'  {len(data)},  // data_size\n')
            f.write(f'  {icon["map_name"]},  // data\n')
            f.write('};\n\n')
    
    print(f'✓ Generated {output_c}')
    print(f'\n✅ Total icons: {len(icons_data)}')


if __name__ == '__main__':
    if len(sys.argv) < 4:
        print(__doc__)
        sys.exit(1)
    
    icons_dir = sys.argv[1]
    output_c = sys.argv[2]
    output_h = sys.argv[3]
    
    if not os.path.isdir(icons_dir):
        print(f'Error: Icons directory not found: {icons_dir}')
        sys.exit(1)
    
    generate_icons(icons_dir, output_c, output_h)
